### ISSUE TITLE
Borders overlap in blocks example

### ISSUE THREAD

**Issue by zoechi** [Philipp-M/trui#1]
Is this inentional and correct behavior or is this a bug?

![image](https://github.com/Philipp-M/trui/assets/405837/783dbebf-5668-4017-920a-d22e09240fdc)

**Comment by Philipp-M** [comment]
That's a bug `block("Block inside block").with_borders(BorderKind::Straight)` should have all Borders. But layout is super hacky currently and will likely be overhauled quite a bit. I guess it's an issue with the taffy `Style` in the `widget::block::Block::layout` implementation

**Comment by zoechi** [comment]
Good to know.
Should we close the issue or leave leave it open?

**Comment by Philipp-M** [comment]
This can stay open, it's not fixed :)
I *think* it has to do with rounding the widget rect while in `Widget::paint` (don't ask me why it's calculated there, as said layout etc. is hacky currently).
As resizing the window sometimes (roughly half of the time) leads to the correct result.
I think this will be fixed by a bigger internal restructure/refactor of the layout.

**Comment by Philipp-M** [comment]
Hmm I think this is fixed with the box-constrained layout change (it does look different/has different behavior though)

**Comment by Philipp-M** [comment]
At the latest since #8 this should be fixed.
